######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 22 15:02:08 2017
######################################################################

TEMPLATE = app
TARGET = raft
DEPENDPATH += .
INCLUDEPATH += .
QT += network
QT += widgets
CONFIG += sdk_no_version_check

# Input
HEADERS += main.hh
SOURCES += main.cc
